In [2]:
import joblib

import pandas as pd

In [3]:
df=pd.read_csv("Traning_Dataset.csv")
df.head()

,Student_ID,Student_Name,Lesson_ID,Lesson_Name,Quiz_1_Score,Quiz_2_Score,Quiz_3_Score,Quiz_Average,Followup_Quiz_Score,Lesson_Wise_Term_Test_Score
0,ST001,Nimal Perera,1,Information and Communication Technology,0.0,30.0,15.0,15.00,65.0,15.0
1,ST001,Nimal Perera,2,Fundamentals of a Computer System,20.0,25.0,35.0,26.67,60.0,16.0
2,ST002,Kasun Silva,1,Information and Communication Technology,45.0,60.0,30.0,45.00,90.0,29.0
3,ST002,Kasun Silva,2,Fundamentals of a Computer System,25.0,25.0,15.0,21.67,90.0,18.0
4,ST003,Sahan Jayasuriya,1,Information and Communication Technology,35.0,30.0,35.0,33.33,70.0,26.0

In [4]:
df.isnull().sum()

Student_ID                     0
Student_Name                   0
Lesson_ID                      0
Lesson_Name                    0
Quiz_1_Score                   4
Quiz_2_Score                   4
Quiz_3_Score                   4
Quiz_Average                   4
Followup_Quiz_Score            4
Lesson_Wise_Term_Test_Score    4
dtype: int64

In [6]:
df[df.isnull().any(axis=1)]

,Student_ID,Student_Name,Lesson_ID,Lesson_Name,Quiz_1_Score,Quiz_2_Score,Quiz_3_Score,Quiz_Average,Followup_Quiz_Score,Lesson_Wise_Term_Test_Score
6,ST004,Dinesh Fernando,1,Information and Communication Technology,NaN,NaN,NaN,NaN,NaN,NaN
7,ST004,Dinesh Fernando,2,Fundamentals of a Computer System,NaN,NaN,NaN,NaN,NaN,NaN
21,ST011,Isuru Karunaratne,2,Fundamentals of a Computer System,NaN,NaN,NaN,NaN,NaN,NaN
29,ST015,Dilshan Peris,2,Fundamentals of a Computer System,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.isna().sum()

Student_ID                     0
Student_Name                   0
Lesson_ID                      0
Lesson_Name                    0
Quiz_1_Score                   4
Quiz_2_Score                   4
Quiz_3_Score                   4
Quiz_Average                   4
Followup_Quiz_Score            4
Lesson_Wise_Term_Test_Score    4
dtype: int64

In [7]:
df[df.isnull().any(axis=1)]

,Student_ID,Student_Name,Lesson_ID,Lesson_Name,Quiz_1_Score,Quiz_2_Score,Quiz_3_Score,Quiz_Average,Followup_Quiz_Score,Lesson_Wise_Term_Test_Score
6,ST004,Dinesh Fernando,1,Information and Communication Technology,NaN,NaN,NaN,NaN,NaN,NaN
7,ST004,Dinesh Fernando,2,Fundamentals of a Computer System,NaN,NaN,NaN,NaN,NaN,NaN
21,ST011,Isuru Karunaratne,2,Fundamentals of a Computer System,NaN,NaN,NaN,NaN,NaN,NaN
29,ST015,Dilshan Peris,2,Fundamentals of a Computer System,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(59, 10)

In [7]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.model_selection import train_test_split
features=['Module_1_Score','Module_2_Score','Module_3_Score','Avg_Module_Score','Followup_Quiz_Score']   
X=df[features]
y=df['Actual_Term_Test_Score']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=RandomForestRegressor()
model.fit(X_train,y_train)

y_predict=model.predict(X_test)
print("r2 score:",r2_score(y_test,y_predict))

r2 score: 0.9460796584210097

In [8]:
joblib.dump(model, "term_score_predictor.pkl")

print("Model saved successfully!")

Model saved successfully!

In [9]:
loaded_model = joblib.load("term_score_predictor.pkl")

sample = [[85, 92, 86, 87.67, 89.67]]

prediction = loaded_model.predict(sample)

print(prediction)

[87.7821]

C:\Users\User 01\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(